### ISSUE TITLE
Show more info

### ISSUE THREAD

**Issue by cedenoaugusto** [minodisk/bigquery-runner#10]
Hi,
It works perfect to me. thanks a lot.
But, when create a procedure: ie: CREATE OR REPLACE PROCEDURE 
It does not show resutls. 3 windows are opened on blank.
Can we work together on this?
Regards

**Comment by minodisk** [comment]
In the meantime, I'll note what I've confirmed.

- It throws an error when I run it.
- Three blank tabs are created.
- As far as the web UI is concerned, there may not be much information to display.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/514164/168113819-8c299de3-664a-4b9a-933d-5fb5beee83b1.png">
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/514164/168114022-25925654-5ead-4fa0-b2a1-34b171808aca.png">

**Comment by minodisk** [comment]
@cedenoaugusto 
I made it possible to display the result of create procedure.
Try v0.0.53.
![image](https://user-images.githubusercontent.com/514164/173191314-623024f0-9f70-4593-98b6-ee22b7ccb808.png)

**Comment by cedenoaugusto** [comment]
hi @minodisk 
great news! 
regards
