### ISSUE TITLE
SQL variables

### ISSUE THREAD

**Issue by sebastianfuchsprivate** [minodisk/bigquery-runner#14]
When I use variables in my SQL (DECLARE <name> TYPE DEFAULT <value>;) I always get:
 [{
	"resource": "mysql.bqsql",
	"owner": "bigqueryRunner",
	"severity": 8,
	"message": "Error: no routine",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 150,
	"endColumn": 21
}]
as output.
Hardcoding works nicely.

**Comment by minodisk** [comment]
# Minimum query for reproduction

```
DECLARE x NUMERIC(10) DEFAULT 12345;

SELECT x AS x;
```

# Result

![image](https://user-images.githubusercontent.com/514164/177250750-976a7342-2c92-44a5-bb30-b00d5dbf1a06.png)

**Comment by minodisk** [comment]
@sebastianfuchsprivate 

It's fixed in v1.0.0, try it!

<img width="927" alt="image" src="https://user-images.githubusercontent.com/514164/177574269-71ec3988-485c-4991-8680-8aa2fc68e2ac.png">

**Comment by sebastianfuchsprivate** [comment]
@minodisk - works like a charm on my queries! Thank you very much for the extremly quick turn-around.
