### ISSUE TITLE
Support `dataset_id` for default dataset

### ISSUE THREAD

**Issue by dvdsgl** [minodisk/bigquery-runner#21]
Please add a setting for `dataset_id` to allow a default dataset in queries: 

```shell
$ bq query --dataset_id=foo 'select * from bar'
# Equivalent to
$ bq query 'select * from foo.bar'
```

Thank you for your work on this!

**Comment by minodisk** [comment]
@dvdsgl 

I've implemented [defaultDataset.datasetd](https://github.com/minodisk/bigquery-runner/blob/main/README.md#bigqueryrunnerdefaultdatasetdatasetid) and released it in [v1.8.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v180), give it a try!

![image](https://user-images.githubusercontent.com/514164/179751508-d5997f84-e1be-40a2-9b44-e8ef0a39136d.png)

**Comment by dvdsgl** [comment]
Works great! Thank you 😃

**Comment by minodisk** [comment]
Thanks for trying it!!! And thank you for sponsoring me 🍻
