### ISSUE TITLE
Feature Request: Authenticate using gcloud CLI

### ISSUE THREAD

**Issue by henryturner27** [minodisk/bigquery-runner#28]
Hello! Thank you so much for your work on this project - it has been immensely helpful to myself and my team <3

One sticking point that has prevented us from using your extension more widely is that we can't authenticate as ourselves through the gcloud CLI. We want to be able to tell who is running a query for auditing purposes and would prefer not to create additional service account keys if possible.

I'll happily submit a PR if that's easiest :)

Thanks again!

**Comment by minodisk** [comment]
@henryturner27 
Hello! Thanks for using BigQuery Runner.

BigQuery Runner supports [ADC](https://google.aip.dev/auth/4110), a mechanism for passing credentials to third-party applications using SDKs like BigQuery Runner.

1. Run [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default).
1. Set `bigqueryRunner.projectId` in `setting.json`.

- Don't specify `bigqueryRunner.keyFilename` in `setting.json`.
- Don't specify `GOOGLE_APPLICATION_CREDENTIALS` as an environment variable.

This is the way it works in my environment. Will it solve what you want to do?

![image](https://user-images.githubusercontent.com/514164/184276546-d092f22b-7973-4740-9db6-0547556fe9a6.png)

**Comment by henryturner27** [comment]
Yes this works perfectly for us. Thanks so much for the help!

**Comment by minodisk** [comment]
Thanks for trying 😉 
I'll add this authentication method to the README as well.

**Comment by minodisk** [comment]
Added https://github.com/minodisk/bigquery-runner/blob/main/README.md#gcloud-credential-recommended .
