### ISSUE TITLE
Feature request: Adding column meta data in the resource list

### ISSUE THREAD

**Issue by GaryLiuTelus** [minodisk/bigquery-runner#30]
Thank you very much for this amazing extension, so that we can leverage powerful capabilities of vscode when working with BigQuery. 

Can you please consider adding column meta data in the resource list? And adding auto complete if possible? Remembering and typing all table names and column names are painful and easy to make mistakes. Adding all column names and types in the list will be very helpful to avoid mistakes. If possible, adding auto-complete will be even better. 

Thanks again for all your efforts!

**Comment by GaryLiuTelus** [comment]
And one more thing, is that possible to add more than one project in the resource list? I am involved into multiple projects and need to join tables from several projects other than my main project. 
Thanks!

**Comment by minodisk** [comment]
@GaryLiuTelus 
I see the responsibility of this extension as being about **running queries**.
I am not currently looking to implement support for **writing queries** in this extension, which seems closer to the LSP category.

**Comment by GaryLiuTelus** [comment]
Thanks for the reply. I think it make sense to me not implementing auto-complete. 

But is that possible to show columns in the resource list? so I don't need to switch between vscode and browser back and forth to check column names. 

Thanks!

**Comment by minodisk** [comment]
Okay, that sounds kind of good. I'd like to get to know your idea better, so let me ask you a question. Which view is the resource list you are talking about? Also, I see the Schema on the Table tab of the Run Result view, but is that not enough?

**Comment by GaryLiuTelus** [comment]
Thank you very for your considerations. 
Below is from DBeaver, a general database client. You can see under each table, it shows a child tree of column names, types etc.
![image](https://user-images.githubusercontent.com/39339422/192556192-429a0829-5845-4dcd-a2dd-f64c45e03e06.png)
While in resource list in Bigquery Runner, the most granular level is table (Project -> Dataset -> Table). 
![image](https://user-images.githubusercontent.com/39339422/192556706-218b6266-abba-4d26-b48e-98fe0eecb53e.png)

Can you please add one more layer down under table, and add column names and types? Like DBeaver? 

Really appreciate!

**Comment by minodisk** [comment]
めちゃ良さそう！
ちょっと時間があるときに試してみるね。

**Comment by minodisk** [comment]
Looks so good! I'll have to give it a try when I have time.

**Comment by minodisk** [comment]
I've released it as v1.13.0, so please use it and FB.
I'll think a bit about what to do with `RECORD` and `STRUCT`.

![Fields in resources view](https://user-images.githubusercontent.com/514164/192826579-fe9127fe-4563-47a5-80a8-3b49219bd947.png)

**Comment by GaryLiuTelus** [comment]
Thank you very much! this looks so beautiful!

**Comment by minodisk** [comment]
Added icons in [v1.17.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1170).

![image](https://user-images.githubusercontent.com/514164/196463784-f4126833-dc56-4d27-9596-caae3a502adf.png)

**Comment by minodisk** [comment]
I'm closing because I did everything I could 😄
