### ISSUE TITLE
Feature Request : Add a config option to use the gcloud proxy

### ISSUE THREAD

**Issue by jetdragon** [minodisk/bigquery-runner#31]
This is amazing extension, I can use it in daily work with bigquery.

Is it possible to add a config option to let the extension to use the "gcloud proxy"? My company has an enterprise proxy for gcp, I found i need to setup the vscode's proxy to it , otherwise the extension can't access gcp. But unfortunetly , the gcp proxy is different with the internet proxy, if I change the vscode proxy setting, other extensions can't access internet. So could you consider to add a config option to use the gcp proxy? or can let the extention to read the existing gcloud config option to get the gcloud proxy ?

**Comment by minodisk** [comment]
@jetdragon 

Thanks for using.

I don't think BigQuery's SDK supports setting up a Proxy 😭 
https://github.com/googleapis/nodejs-bigquery/issues/1021

If you find any useful documentation or issues, please let me know.
