### ISSUE TITLE
Query: Required parameter is missing

### ISSUE THREAD

**Issue by smfritzii** [minodisk/bigquery-runner#38]
I've gone through the process of installing & configuring the extension according to the extension page.

First issue: There is no Bigquery Runner: Login command....

but I set  "bigqueryRunner.keyFilename": to my service account json file & it seems to be fine, it gets a list of datasets in my project.

But if I try to run the most basic query (select * from `project.ds.table` limit 100) or to use the "Preview" option in the side pane, I get the error in the title. 

What is missing?

**Comment by PURPLE-YO** [comment]
I had the same issue with the default login method. Didn't set bigqueryRunner.keyFilename. The error of "Query: Required parameter is missing" keeps showing even without a query written...

**Comment by crmne** [comment]
I have the same issue

**Comment by minodisk** [comment]
@PURPLE-YO @crmne 
Is `bigqueryRunner.projectId` set?

**Comment by crmne** [comment]
@minodisk yes, with the project name

**Comment by PURPLE-YO** [comment]
> 

yes - projectId and name were all set.

**Comment by Jaunson** [comment]
having the issue here - would love to use this extension but can't seem to debut the issue because of how vague the error message is.

**Comment by minodisk** [comment]
Try [v1.12.1](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1211).

**Comment by crmne** [comment]
@minodisk still has the same problem

**Comment by minodisk** [comment]
@crmne 

We do not have a good understanding of what conditions cause errors. Can you post a screenshot of the entire VSCode of the case where the error occurs?
And either any query won't pass or it errors in a specific case?

**Comment by Anonth** [comment]
I also faced this issue and quickly fix by granting "BigQuery Job User" permission to the Service Account.

**Comment by minodisk** [comment]
@Anonth Thanks for reporting back! I'll reproduce it and improve the message.

**Comment by xnoar747** [comment]
Unfortunately I have the same problem. I have tried different login methods with and without bigqueryRunner.keyFilename and service account respectively.

"bigqueryRunner.projectId" and "bigqueryRunner.defaultDataset.projectId" are set.

In case it's relevant, I also can't query a freely available dataset from BigQuery like bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2019.
The project is loaded in the extension, so I can see all the datasets and tables on the left side. However, when I want to view a preview by right-clicking on it, I get the same error message.

**Comment by lightlySkewed** [comment]
I solved this issue by modifying the settings.json for the user. Specifically, I removed the "bigqueryRunner.defaultDataset.projectId" line, and added the "bigqueryRunner.projectId". Seems to work well, now.
