### ISSUE TITLE
[BUG] - Error Message Parse error: Unexpected "@@row_coun"

### ISSUE THREAD

**Issue by prernaprakash** [minodisk/bigquery-runner#41]
Hi There,

I am unable use the command @@row_count using the extension.
I get the error message **Parse error: Unexpected "@@row_coun" at line 6 column 8**.

Here is a snippet of the code I am using. This code works perfectly on the bigquery console itself
`select
    count(1)
from
    `<project-name>.<dataset>.<tablename>`;
select @@row_count;`

This is true when using any of the System variables reference. For example the below code also throws an error

`select
    count(1)
from
       `<project-name>.<dataset>.<tablename>`;
select @@current_job_id`

ERROR : Parse error: Unexpected "@@current_" at line 6 column 8

**Comment by minodisk** [comment]
I didn't even know this existed 🤔 
[System variables reference](https://cloud.google.com/bigquery/docs/reference/system-variables?hl=en)

**Comment by minodisk** [comment]
@prernaprakash 
Released as [v1.21.4](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1214). Please try it.
