### ISSUE TITLE
how to switch project id

### ISSUE THREAD

**Issue by nqian-curated** [minodisk/bigquery-runner#42]
My Bigquery need to access multi projects. In Bigquery web console, I can see all projects/schemas/tables but in bigquery-runner only one project.
Is there a way to access all projects?

**Comment by minodisk** [comment]
It can be done in two ways.
Create a multi-project service account in GCP and set it to keyFilename.
Or add the account as a principal to the multi-project IAM.
![image](https://user-images.githubusercontent.com/514164/224494545-1337c6ed-3159-44c4-b2b9-57f396b97984.png)

**Comment by ivan-toriya** [comment]
@minodisk 
Feature request, related to the issue:

I'm using service-account with access to multiple projects.
Would it be possible to add all projects and datasets accessible by this service account to the Activity Bar?
Right now, it's only the one where account was created (I guess)
![image](https://user-images.githubusercontent.com/43750521/231448491-4f36ec6a-16ef-444d-9177-4b2a153f1c79.png)

**Comment by minodisk** [comment]
@ivan-toriya 
Try [`bigqueryRunner.tree.projectIds`](https://github.com/minodisk/bigquery-runner#bigqueryrunnertreeprojectids).
It works in my case.

![image](https://user-images.githubusercontent.com/514164/231472974-c57bd5bf-4755-4ad6-b947-cb68d156d2c6.png)
![image](https://user-images.githubusercontent.com/514164/231473010-62823146-434d-4589-82fb-920c7bb5fe9d.png)

**Comment by ivan-toriya** [comment]
@minodisk 
Thanks! That's what I needed!
Forgot to check this in the README 🙈

**Comment by minodisk** [comment]
@ivan-toriya 
If you find any other FBs for existing functions, please raise an issue 😉
