### ISSUE TITLE
Feature request: Add "Open on Remote" button

### ISSUE THREAD

**Issue by ivan-toriya** [minodisk/bigquery-runner#43]
**Feature request**
Add "Open on Remote" button to Activity Bar -> BigQuery Runner -> Resources/Project/Table or View.
Similar to files in Source Control
![image](https://user-images.githubusercontent.com/43750521/231734368-b905c186-7847-4207-b777-244da69f0117.png)

The link that's working for me: `https://console.cloud.google.com/bigquery?p={project_id}&d={dataset}&t={table_or_view_name}&page=table`

\+ the existing "Preview Table" right-click option can be added as a button as well.

**Why?**
"Open on Remote" button can be usefull, if I want to jump quickly into the BQ editor to debug or query something related to the table/view

**Alternative**
"Query: In new file" button. Which creates a new (not saved) file with "SELECT  FROM `` LIMIT 1000" (similar to BQ UI). And then you can run it after changing it to what you need (similar to BQ UI).

**Comment by minodisk** [comment]
Released as [v1.21.3](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1213).
Please try it.

![image](https://github.com/minodisk/bigquery-runner/assets/514164/574368c3-a6f1-404a-8a9d-1c07c22c1450)

**Comment by ivan-toriya** [comment]
Working great for me! Thank you!
