### ISSUE TITLE
Auto-suggest not working

### ISSUE THREAD

**Issue by idejuan** [minodisk/bigquery-runner#44]
Hi, 

First of all, congratulations to minodisk for this great extension!

I have installed v.1.21.1 under windows 11 with Visual Code v.1.78.1

I have followed the tutorial at https://developers.refinitiv.com/en/article-catalog/article/run-google-bigquery-sql-with-vscode but I cannot achieve the same features as explained in that webpage.

- Auto-suggest does not work
- I do not see the button to run the query at the top right of the screen
- When I create a new file, I cannot find the language SQL(BigQuery) (sql-bigquery) 

Thank you for your help

Ignacio

**Comment by lightlySkewed** [comment]
Agree with idejuan. Great extension. Seems to work very well. That said, autocompletion of either a dataset from a project, or a table from a dataset does not seem to work. In addition, if I fully define a table (e.g., `project.dataset.mytable`) in the FROM portion of my query, I don't get autocompletion in the SELECT portion. So if my table has 3 columns (alpha, bravo, charlie), and I type 'a' on line two of the query here:

`
SELECT
    a<typing this>
FROM
    project.dataset.mytable
`
    
I won't see 'alpha' in the resulting autocomplete choices.

Running BigQuery Runner version 1.21.1 on VSCode version 1.75.1 on a Mac.

**Comment by minodisk** [comment]
I know this plugin doesn't support autocomplete. There is no mention of autocompletion in the [README](https://github.com/minodisk/bigquery-runner/blob/main/README.md).

This plugin is focused on query execution.

**Comment by minodisk** [comment]
@idejuan 

> - I do not see the button to run the query at the top right of the screen
> - When I create a new file, I cannot find the language SQL(BigQuery) (sql-bigquery)

There are two simple options.
The first is to set the query file extension to `.bqsql`.
The second is to give the file extension of the query file you want to run to [`bigqueryRunner.extensions`](https://github.com/minodisk/bigquery-runner/blob/main/README.md#bigqueryrunnerextensions) in settings.json.

![image](https://github.com/minodisk/bigquery-runner/assets/514164/2ef6d375-0240-4111-a089-179d183b7a28)
