### ISSUE TITLE
Hashed Value for Table ID

### ISSUE THREAD

**Issue by lightlySkewed** [minodisk/bigquery-runner#45]
Hello,

When previewing a table in VSCode using BigQuery Runner, I see the correct projectId, but the dataset and table end up displaying as random hashes instead of the correct values. For example, if I browse to `myproject.mydataset.mytable` in the BQ Runner Extension Resources pane, right click on a table and select Preview Table, the Table tab of the resulting output will have a Table ID value of `myproject._lotsofnumbersandletters_.anonlotsofnumbersandletters`

I would expect to see `myproject.mydataset.mytable`

I'm currently running BQ Runner version 1.21.1 and VSCode version 1.75.1 on a Mac.

**Comment by minodisk** [comment]
@lightlySkewed 

BigQuery stores query results in temporary tables, so it's not wrong that the IDs of the temporary tables are displayed.
On the other hand, I understand that you want the original table information to be displayed in the preview. I'll change the preview to show the original table information.

**Comment by lightlySkewed** [comment]
@minodisk 

Ah! Thank you! That would be amazing. 

So then when I click on BigQuery Runner: Preview Table, it's actually running a query on the table to generate the preview?

![Image 7-1-23 at 8 21 AM](https://github.com/minodisk/bigquery-runner/assets/77297259/f500d1d9-cc8e-42ce-81da-4f7a50218d3f)

**Comment by minodisk** [comment]
Yup. 

![image](https://github.com/minodisk/bigquery-runner/assets/514164/e81d7850-31fc-4d04-8fbc-6f246b5ed94d)

**Comment by minodisk** [comment]
@lightlySkewed 
[Published](https://github.com/minodisk/bigquery-runner/actions/runs/5432115106) as 1.21.2. Please try it.

**Comment by lightlySkewed** [comment]
Hi Diasuke,

I'm now on version 1.21.4, and still see the same random hashes for table
numes. Also, I don't see a 1.21.2 version in VSCode's available versions.
Sorry for all the trouble.

[image: image.png]
Best,
Mike

**Comment by minodisk** [comment]
v1.21.4 is fine. I think it's working, but you may need to restart VSCode once.

![image](https://github.com/minodisk/bigquery-runner/assets/514164/bfed86c2-83ea-4b6e-9bbe-be8976edff47)
