### ISSUE TITLE
{"error":"invalid_grant","error_description":"reauth related error (rapt_required)","error_uri":"https://support.google.com/a/answer/9368756","error_subtype":"rapt_required"}

### ISSUE THREAD

**Issue by babegeman** [minodisk/bigquery-runner#47]
When I originally installed this extension, I believe it was sharing the VSCode installation of Google CLI from "Cloud Code" and thus when I authenticated in Cloud Code, BigQuery Runner ran perfectly without any additional configuration. However, recently Cloud Code changed its authentication paradigm and now when I attempt to run a query I receive the error in the subject line, repeated here: {"error":"invalid_grant","error_description":"reauth related error (rapt_required)","error_uri":"https://support.google.com/a/answer/9368756","error_subtype":"rapt_required"}

I have attempted to "gcloud auth login" via a terminal in VSCode but it still returns this error. Any ideas?

**Comment by babegeman** [comment]
I may have made a mistake. If I logout and login again it does seem to run code, but it fails to show the tables in the project in the "BigQuery Runner: Resources" pane, giving the above error.

**Comment by minodisk** [comment]
How about trying [Set session length for Google Cloud services](https://support.google.com/a/answer/9368756) as per the error message?
