### ISSUE TITLE
Bug: "Preview Table in VS Code" does not use bigqueryRunner.tree.projectIds with multiple projects

### ISSUE THREAD

**Issue by dzion** [minodisk/bigquery-runner#48]
Thanks for all your work and providing this super helpful extension :) 

While using it today I found the following bug:

Previewing tables in VSCode (via `Bigquery Runner: Preview Table in VS Code`) works well for all tables in the main project (i.e. set in `bigqueryRunner.projectId`).  
However, when the table is in an alternative project from `bigqueryRunner.tree.projectIds`, it seems that the extension is looking for the tables in the project set in `bigqueryRunner.projectId`, rather than using the project set in `bigqueryRunner.tree.projectIds` and thus returns an error if the table is not found or it could even return the wrong table if a table with the same name exists in the main project.

**Comment by minodisk** [comment]
@dzion Thanks for using BigQuery Runner.

`bigqueryRunner.tree.projectIds` is used only for tree display.
The use of `bigqueryRunner.projectId` when executing the query is as specified.
If you want to query for datasets in a project other than `bigqueryRunner.projectId`, you can explicitly specify the `projectId` in the query, such as `select * from projectId.datasetId.tableId`.

**Comment by dzion** [comment]
Hi @minodisk,
I think we might be talking about different things.
I was indeed referring to the tree display (where you can execute the `preview table in VS Code` command from). 
The tree view uses the correctly specified `bigqueryRunner.tree.projectIds` to show datasets, tables and their schemas. However, when you click on a table in the tree view in a different project and try to preview a table, the query is send against the project set in `bigqueryRunner.projectId`, rather than the project in the tree. 
Anyways, if this is your expected behavior, than maybe disabling the `preview table in VS Code` for the tree viewer for tables not in the main project would be a good idea, as it doesn't work currently.
![Screenshot 2024-01-15 at 11 59 09](https://github.com/minodisk/bigquery-runner/assets/10477978/a85f26b8-5371-4f36-a57e-363695de1a61)

**Comment by minodisk** [comment]
@dzion Thank you for sharing the detailed situation. I think it is totally a bug and I will fix it when I have more time.

**Comment by minodisk** [comment]
Fixed in [v1.21.11](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v12111).
![image](https://github.com/minodisk/bigquery-runner/assets/514164/457989ac-1b7c-459f-a62f-93eab166c6ca)

**Comment by dzion** [comment]
Works perfectly on my end too. 
Many thanks 💪 🥳
