### ISSUE TITLE
Add GUI to run queries

### ISSUE THREAD

**Issue by Matts966** [minodisk/bigquery-runner#5]
Can a Pull request to add GUI button to run queries be accepted?

**Comment by minodisk** [comment]
Where do you plan to put the GUI buttons?
If it is in the viewer's WebView, it seems difficult.
Because the viewer only renders the data it receives and is not connected to the query.

**Comment by Matts966** [comment]
That can be above the sql file like debug button?

**Comment by minodisk** [comment]
Like this?
![image](https://user-images.githubusercontent.com/514164/156711950-422e263a-ef93-48ed-b62b-77f2297f633d.png)

I don't know much about the VSCode API here, but it sounds sooooo good ❤️ 
If you make a PR, I want to merge.

**Comment by minodisk** [comment]
Maybe in the next version:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/514164/161435078-21a0934a-085c-47ac-aad2-3a64fc075f24.png">

**Comment by minodisk** [comment]
Released [v0.0.44](https://github.com/minodisk/bigquery-runner/blob/b0f01351f899425813ac5f1d13f6780bdca43e39/CHANGELOG.md#v0044).
Paging GUI may be added in the next version.

**Comment by Matts966** [comment]
Great enhancements!!! 🚀
