### ISSUE TITLE
BigQuery Runner Extension EISDIR: Illegal operation on a directory, read

### ISSUE THREAD

**Issue by etrevathan** [minodisk/bigquery-runner#51]
I have been working in the VS Code/GitLab environment for over six months and suddenly am receiving an error in VS Code: EISDIR: Illegal operation on a directory, read. I have worked for hours trying to resolve this error and haven't been able to resolve it. Any assistance is appreciated.

**Comment by minodisk** [comment]
Does this error occur when I run the query? If you can give me more details about the circumstances under which the error occurs, I may be able to help.

**Comment by etrevathan** [comment]
It happens after opening VS Code and clicking on a .bqsql file. I don't have to try to run it to get the error, but I also get the error when I try to run a .bqsql file.

Python is installed and operating correctly.

Eva

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by minodisk** [comment]
@etrevathan 

Would the same error occur after uninstalling BigQuery Runner?

**Comment by etrevathan** [comment]
Yes, it occurs after uninstalling BigQuery Runner. It also occurs after obtaining a different VM and setting everything up from scratch.

**Comment by minodisk** [comment]
@etrevathan 

It seems that BigQuery Runner is not the cause of the error then. I'm afraid I can't help you.

**Comment by etrevathan** [comment]
I don't get the error until I get to the step where I install the BigQuery Runner extension, so I guess I'll just find a replacement for it.

**Comment by minodisk** [comment]
Unfortunately, that sounds better for you.
