### ISSUE TITLE
Big Int are all rounded in the returned results

### ISSUE THREAD

**Issue by GaryLiuTelus** [minodisk/bigquery-runner#54]
In the result grid, if a number is very big, the displayed numbers are all rounded.
The results displayed in the web console: 
![image](https://github.com/minodisk/bigquery-runner/assets/39339422/d1a91738-e729-4c01-bd79-b4dfed75f233)

The same result displayed in the vscode BQ runner tab, so these 2 different numbers are displayed the same: 
![image](https://github.com/minodisk/bigquery-runner/assets/39339422/c7a0b782-0e59-4a72-850f-e6ad9f2220ad)

The column type is INT64
![image](https://github.com/minodisk/bigquery-runner/assets/39339422/66a91a69-a094-4cb7-ad7a-6a2d80104ccd)

**Comment by minodisk** [comment]
`9162371277713859723`
`9162371277713859735`

**Comment by minodisk** [comment]
I think I overflowed with JavaScript's Number, I'll try to fix it with BigInt.
![image](https://github.com/minodisk/bigquery-runner/assets/514164/f66b8e5f-b703-45dc-a43b-f5d6a9cc188b)

**Comment by minodisk** [comment]
@GaryLiuTelus 
I have published [v1.21.13](https://marketplace.visualstudio.com/items?itemName=minodisk.bigquery-runner) which fixes this problem, so give it a try!

**Comment by GaryLiuTelus** [comment]
Thank you so much for such swift response!
