### ISSUE TITLE
exporting to .csv omits column headers 

### ISSUE THREAD

**Issue by kairos-j-alo** [minodisk/bigquery-runner#58]
Hi!  great tool.  However when I use the function to export my query results to .csv, it omits the headers.  Is there a workaround to this? am i missing something?  would really appreciate the help :)

**Comment by minodisk** [comment]
@kairos-j-alo 
Hi! Thanks for using BigQuery Runner.
Try the [CSV header option](https://github.com/minodisk/bigquery-runner/blob/main/README.md#bigqueryrunnerdownloadercsvheader) in `settings.json`:

```json
{
  "bigqueryRunner.downloader.csv.header": true
}
```

**Comment by kairos-j-alo** [comment]
It worked perfectly thanks!  Keep up the good work!
